Update Halo MCC to add notes about functionality
Starz0r/AreWeAntiCheatYet pull request #1025
Opened 2022-12-19 05:23 UTC by udekmp

I added notes that specify that:
"Singleplayer, co-op, and custom matches work"

2022-12-19 06:50 UTC, Curve requested changes

2022-12-19 06:50 UTC, Curve commented on games.json
> +        Singleplayer, co-op, and custom matches work
Invalid formatting

2022-12-19 19:57 UTC, udekmp commented
I may have still formatted incorrectly... but I attempted to fix it.

2022-12-19 19:59 UTC, Curve commented
Yep still wrong, I'll change it manually

2022-12-19 20:04 UTC, merged

2022-12-21 02:02 UTC, udekmp commented
> Yep still wrong, I'll change it manually

Thank you!